### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by qoiz12** [Bonzey2416/RectifyCSS#1]
The existing download button does not link to any page. Replace the existing button with the following code to fix this issue.
 `<button type="button" class="btn btn-primary" onclick="document.location='https://github.com/Bonzey2416/RectifyCSS/archive/refs/tags/v0.4-alpha.zip'">Download</button>`
(Add this code if you want the download button to link to the latest release).

**Comment by Bonzey2416** [comment]
Thanks, I'll fix that.

**Comment by qoiz12** [comment]
No Problem!
